### ISSUE TITLE
Bug with Scan Game files output in the GUI

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/Buffout4-CLAS#32]
There is a bug in Scan_Interface where it will output the list of error logs in the FO4 install directory as a raw python list, complete with the \n-----\n parts. I found it in the course of testing my latest PR.

Example of output: 
`['E:\\Games\\Steam\\steamapps\\common\\Fallout 4\\CreationKit.exe_20220511_062845.log\n-----\n', 'E:\\Games\\Steam\\steamapps\\common\\Fallout 4\\CreationKit.exe_20220511_063707.log\n-----\n', 'E:\\Games\\Steam\\steamapps\\common\\Fallout 4\\xSE PluginPreloader.log\n-----\n']`

In the terminal window, it is all on a single line.

I've verified that this happens on Python versions 3.11 (my primary python install) and 3.9
Also confirmed it happens even without my changes to Scan_Gamefiles.py

**Comment by GuidanceOfGrace** [comment]
Let me know if this is still a problem with **v6.35**

**Comment by evildarkarchon** [comment]
Seems to be fixed.
