### ISSUE TITLE
False Negatives in Core_Mods section

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/Buffout4-CLAS#44]
I've got a report of some false negatives in the core_mods section. WARNING: this log mentions some NSFW mods.
The most obvious false negatives are UFO4P, PRP, and Canary Save Monitor. It also seems to be checking for both Vulkan Renderer and Nvidia Reflex, the person in question has an Nvidia card. It seems to find "Weapon Debris Crash Fix" and "High FPS Physics Fix" just fine.
Here's the log and scan:
[crash-2023-03-23-00-34-01 - Kaiiiiiii.log](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/11050015/crash-2023-03-23-00-34-01.-.Kaiiiiiii.log)
[crash-2023-03-23-00-34-01 - Kaiiiiiii-AUTOSCAN.md](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/11050016/crash-2023-03-23-00-34-01.-.Kaiiiiiii-AUTOSCAN.md)
When I printed out section_plugins, it returned the output I expected, a list() with the list of plugins from the "PLUGINS" section.

**Comment by GuidanceOfGrace** [comment]
Once again, I need to pay attention which variables are lists and which are strings...
Will be fixed for the next update.

**Comment by evildarkarchon** [comment]
github copilot very helpfully constructed some special conditions for the vulkan/weapons debris crash fix/nvidia refex sections of core_mods (they could probably be consolidated, but this version is more readable):
`if mod_name == 'Weapon Debris Crash Fix' and gpu_nvidia == False:
    continue
elif mod_name == 'Nvidia Reflex Support' and gpu_nvidia == False:
    continue
elif mod_name == 'Vulkan Renderer' and gpu_amd == False:
    continue`

**Comment by evildarkarchon** [comment]
You might want to use special conditions for the vulkan, weapons debris crash fix, and nvidia reflex mods for when they are detected in improper circumstances (reflex/debris fix on non-nvidia cards or vulkan on non-amd cards) because at this time, they just show as not found when the conditions are not met. Just thought of it when I was making my temporary hotfix version because github copilor was feeling extra helpful.
