### ISSUE TITLE
FCX Mode checks crash logs even though it's not supposed to

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/Buffout4-CLAS#52]
When I was running tests on my experimental branch (which is in PR #51) I noticed that FCX mode was printing from crash logs in the Documents F4SE directory even though it isn't supposed to, I tested on the latest main branch code, and it exhibits the same problem.

**Comment by GuidanceOfGrace** [comment]
If I understand correctly and if you mean FCX Mode detecting errors from logs in F4SE folder, but that also includes crash logs, then I noticed that recently as well. I'll look over it once I merge your changes.

**Comment by evildarkarchon** [comment]
yes, that is the issue
