### ISSUE TITLE
Buffout4 config filename change

### ISSUE THREAD

**Issue by kanguru-au** [GuidanceOfGrace/Buffout4-CLAS#60]
`CLAS_Database.py` says to change values in `Buffout4.toml` to improve configuration, e.g.
> `FIX: Open *Buffout4.toml* and change F4EE parameter to TRUE, this prevents bugs and crashes from Looks Menu.`

Didn't Buffout4 change its logfile to `config.toml` though? I've been editing and editing `Buffout4.toml` and it didn't change the CLAS messages so I finally had a look for the reason behind that misbehaviour.

Also, CLAS talks about "culprits" when it should be using another word like "suspects". A culprit is a person who is _responsible_ for a crime or other misdeed, not one suspected of a misdeed. Words matter.

**Comment by GuidanceOfGrace** [comment]
Yes, latest versions of Buffout4 changed the config file to config.toml, so the current Nexus release is out of date for every BO4 version above 1.26.2 until I release the new version. The Py scripts on Git here should work just fine tho. And yeah, "suspects" definitely fits better.
